name: leads_manager
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #audioplayers: ^0.20.1
  bottom_picker: ^2.3.3
  bubble: 1.2.1
  cached_network_image: ^3.3.0
  calendar_date_picker2: ^0.5.5
  call_log: ^4.0.0
  carousel_slider: 4.0.0
  charts_flutter: ^0.12.0
  chat_bubbles: 1.4.0
  chewie: 1.1.0
  cloud_firestore: ^3.4.4
  connectivity: ^3.0.6
  connectivity_plus: ^5.0.2
  cupertino_icons: 1.0.3
  curved_navigation_bar: ^1.0.3
  custom_searchable_dropdown: 2.1.1
  date_time_picker: 2.1.0
  dio: 4.0.0
  dropdown_textfield: ^1.0.8
  easy_debounce: ^2.0.3
  emoji_picker_flutter: 1.1.2
  excel: ^4.0.2
  file_picker: null
  file_picker_cross: ^4.4.1
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  firebase_crashlytics: ^2.8.8
  firebase_messaging: ^11.2.11
  fl_chart: ^0.36.4
  flutter:
    sdk: flutter
  flutter_app_version_checker: ^0.3.2
  flutter_background_service: 2.4.4
  flutter_cache_manager: ^3.3.0
  flutter_dropdown: ^1.0.1+hotfix.1
  flutter_easyloading: 3.0.3
  flutter_linkify: 5.0.2
  flutter_local_notifications: 9.4.0
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.7
  flutter_typeahead: 4.8.0
  flutter_widget_from_html_core: 0.8.5+1
  fluttertoast: 8.2.2
  get: 4.6.1
  google_fonts: ^4.0.4
  http: 0.13.4
  image_cropper: 1.4.1
  image_picker: 0.8.2
  intl: 0.17.0
  logger: ^2.1.0
  mqtt_client: ^10.2.1
  multi_dropdown: ^1.0.2
  multi_select_flutter: 4.1.1
  path_provider: any
  permission_handler: 8.1.6
  phone_state_background: ^0.0.4
  provider: ^6.0.5
  scrollable_positioned_list: ^0.3.8
  searchfield: ^1.0.1
  share_plus: 4.0.4
  shared_preferences: 2.0.6
  simple_rich_text: 2.0.49
  sms_autofill: 2.3.0
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  syncfusion_flutter_charts: ^21.2.4
  table_calendar: ^3.0.8
  textfield_search: ^0.10.0
  universal_html: ^2.2.2
  url_launcher: 6.0.10
  uuid: ^3.0.1
  video_player: ^2.2.10
  video_player_web: null
  web_socket_channel: ^2.4.0
  webview_flutter: 2.0.0

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launchericon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/icon/
    - assets/sounds/sentSound.mp3
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
